### ISSUE TITLE
error CS1503: Argument 1: cannot convert from 'void*' to 'int*'

### ISSUE THREAD

**Issue by parsue** [AnnulusGames/BurstLinq#5]
Mulitple lines error in following files:
Library\PackageCache\com.annulusgames.burst-linq@bd8729e0f4\Runtime\BurstLinqExtensions.Native.Average.cs
Library\PackageCache\com.annulusgames.burst-linq@bd8729e0f4\Runtime\BurstLinqExtensions.Native.Contains.cs
Library\PackageCache\com.annulusgames.burst-linq@bd8729e0f4\Runtime\BurstLinqExtensions.Native.Max.cs
Library\PackageCache\com.annulusgames.burst-linq@bd8729e0f4\Runtime\BurstLinqExtensions.Native.Min.cs
Library\PackageCache\com.annulusgames.burst-linq@bd8729e0f4\Runtime\BurstLinqExtensions.Native.SequenceEqual.cs
-----
Unity version 2023.2.13.f1
Burst: 1.8.12

**Comment by ckocank** [comment]
same error

**Comment by nuskey8** [comment]
This error seems to be caused by the version of the Collections package. `GetUnsafePtr()` returns `void*` for old Collections.

Looks like I need to add an explicit cast to prevent the error.

**Comment by nuskey8** [comment]
Fixed in #7.
